from .exts import db
from .models import *


def init_db():
    db.drop_all()
    db.create_all()
    
    user1=User(username="user1")
    user2=User(username="user2")

    site1=Site(name="site 1")
    site2=Site(name="site 2")
    site3=Site(name="site 3")
    site4=Site(name="site 4")

    user1.sites.append(site1)
    user1.sites.append(site2)
    user2.sites.append(site3)
    user2.sites.append(site4)

    subject1 = Subject(subject="muzyka")
    subject2 = Subject(subject="gry")
    subject3 = Subject(subject="filmy")
    subject4 = Subject(subject="książki")
    subject5 = Subject(subject="historia")
    subject6 = Subject(subject="socjologia")
    subject7 = Subject(subject="kultura")
    subject8 = Subject(subject="kuchnia")

    site1.subjects.append(subject1)
    site1.subjects.append(subject3)
    site2.subjects.append(subject5)
    site2.subjects.append(subject6)
    site3.subjects.append(subject7)
    site3.subjects.append(subject8)
    site3.subjects.append(subject2)
    site3.subjects.append(subject5)
    site4.subjects.append(subject4)
    site4.subjects.append(subject2)
    site4.subjects.append(subject1)

    gallery1 = Gallery(name="gallery 1", description="gallery description 1", sort=1, site_id=0)
    gallery2 = Gallery(name="gallery 2", description="gallery description 2", sort=1, site_id=1)
    gallery3 = Gallery(name="gallery 3", description="gallery description 3", sort=1, site_id=1)
    gallery4 = Gallery(name="gallery 4", description="gallery description 4", sort=1, site_id=1)
    gallery5 = Gallery(name="gallery 5", description="gallery description 5", sort=1, site_id=2)
    gallery6 = Gallery(name="gallery 6", description="gallery description 6", sort=1, site_id=2)
    gallery7 = Gallery(name="gallery 7", description="gallery description 7", sort=1, site_id=2)
    gallery8 = Gallery(name="gallery 8", description="gallery description 8", sort=1, site_id=2)
    gallery9 = Gallery(name="gallery 9", description="gallery description 9", sort=1, site_id=3)
    gallery10 = Gallery(name="gallery 10", description="gallery description 10", sort=1, site_id=3)
    gallery11 = Gallery(name="gallery 11", description="gallery description 11", sort=1, site_id=3)
    gallery12 = Gallery(name="gallery 12", description="gallery description 12", sort=1, site_id=3)
    gallery13 = Gallery(name="gallery 13", description="gallery description 13", sort=1, site_id=4)
    gallery14 = Gallery(name="gallery 14", description="gallery description 14", sort=1, site_id=4)
    gallery15 = Gallery(name="gallery 15", description="gallery description 15", sort=1, site_id=4)
    gallery16 = Gallery(name="gallery 16", description="gallery description 16", sort=1, site_id=4)

    photo1=Photo(filename="111.png", description="description 1", sort=1)
    photo2=Photo(filename="222.png", description="description 2", sort=1)
    photo3=Photo(filename="333.png", description="description 3", sort=1)
    photo4=Photo(filename="444.png", description="description 4", sort=1)
    photo5=Photo(filename="555.png", description="description 5", sort=1)
    photo6=Photo(filename="666.png", description="description 6", sort=1)
    photo7=Photo(filename="777.png", description="description 7", sort=1)
    photo8=Photo(filename="888.png", description="description 8", sort=1)

    gallery1.photos.append(photo1)
    gallery1.photos.append(photo2)
    gallery1.photos.append(photo3)
    gallery1.photos.append(photo4)
    gallery2.photos.append(photo5)
    gallery2.photos.append(photo6)
    gallery2.photos.append(photo7)
    gallery2.photos.append(photo8)

    site1.galleries.append(gallery1)
    site1.galleries.append(gallery2)
    site1.galleries.append(gallery3)
    site1.galleries.append(gallery4)
    site2.galleries.append(gallery1)
    site2.galleries.append(gallery6)
    site2.galleries.append(gallery7)
    site2.galleries.append(gallery8)
    site3.galleries.append(gallery9)
    site3.galleries.append(gallery10)
    site3.galleries.append(gallery11)
    site3.galleries.append(gallery12)
    site4.galleries.append(gallery13)
    site4.galleries.append(gallery14)
    site4.galleries.append(gallery15)
    site4.galleries.append(gallery16)

    db.session.add_all([user1, user2])
    db.session.commit()
    print("DATABASE INITIALIZED")
